version: "3.8"

services:
  mmpca:
    build: .
    working_dir: /package
    volumes:
      - ./package:/package
    environment:
      _R_SHLIB_STRIP_: "false"
    command: >
      R CMD check mmpca_2.0.3.tar.gz --use-valgrind --no-stop-on-test-error