# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_objective <- function(theta, x_list, masks_list, inds, k, p, lambda) {
    .Call(`_mmpca_c_objective`, theta, x_list, masks_list, inds, k, p, lambda)
}

c_grad <- function(theta, x_list, masks_list, inds, k, p, lambda, n_threads) {
    .Call(`_mmpca_c_grad`, theta, x_list, masks_list, inds, k, p, lambda, n_threads)
}

c_Vxi <- function(xi) {
    .Call(`_mmpca_c_Vxi`, xi)
}

c_optim_mmpca <- function(start, x_list, masks_list, inds, k, p, lambda, max_iter, trace, n_threads) {
    .Call(`_mmpca_c_optim_mmpca`, start, x_list, masks_list, inds, k, p, lambda, max_iter, trace, n_threads)
}

c_invVinner <- function(t) {
    .Call(`_mmpca_c_invVinner`, t)
}

c_init_parallel <- function() {
    invisible(.Call(`_mmpca_c_init_parallel`))
}

